# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMClcdAyNUY5dOx1HH4BWiXpKl-umLO8
"""

import streamlit as st
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import matplotlib.pyplot as plt

# Set up the Streamlit page
st.set_page_config(page_title="Handwritten Digit Classifier", layout="centered")
st.title("🖋️ Handwritten Digit Classification using SVM")

# Load and prepare data
@st.cache_data
def load_and_train_model():
    digits = load_digits()
    X, y = digits.data, digits.target

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    model = SVC()
    model.fit(X_train_scaled, y_train)

    return model, scaler, digits

model, scaler, digits = load_and_train_model()

# Choose a digit sample
st.subheader("Choose a Digit Sample")
sample_idx = st.slider("Select an image index", 0, len(digits.images) - 1, 0)
image = digits.images[sample_idx]
data = digits.data[sample_idx]

# Display the digit
st.image(image, caption=f"Digit Label: {digits.target[sample_idx]}", width=150)

# Predict the digit
scaled_data = scaler.transform([data])
prediction = model.predict(scaled_data)[0]
st.success(f"Predicted Digit: {prediction}")
